### PR TITLE
Remove hardcoded python2

### PR DESCRIPTION
**Pull request by elfosardo**

### CODE REVIEW

**Review by dtantsur — APPROVED** [review]
Thanks!

**Comment by metal3ci** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/962/

**Review by derekhiggins — APPROVED** [review]

**Comment by metal3ci** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/971/

**Comment by metal3ci** [comment]
Build SUCCESS, see build http://10.8.144.11:8080/job/dev-tools/973/

**Comment by elfosardo** [comment]
success! \o/

**Pull request merged**
