### PR TITLE
Use master for tripleo repo

### PR DESCRIPTION
**Pull request by elfosardo**

### CODE REVIEW

**Comment by metal3ci** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/1442/

**Comment by maelk** [comment]
random jenkins error, retriggering the tests

**Comment by elfosardo** [comment]
since the change in the ironic-image is merged already, we should move forward with this to avoid having different versions between ironic and ironic-inspector

**Review by dtantsur — APPROVED** [review]
/lgtm

**Pull request merged**
