### PR TITLE
Move to Train branch

### PR DESCRIPTION
**Pull request by elfosardo**
Moving to train branch

### CODE REVIEW

**Review by dtantsur — APPROVED** [review]

**Comment by metal3ci** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/1084/

**Comment by metal3ci** [comment]
Build SUCCESS, see build http://10.8.144.11:8080/job/dev-tools/1085/

**Review by derekhiggins — APPROVED** [review]
lgtm tested on dev-scripts bootstrap and master nodes

**Comment by elfosardo** [comment]
let's hold on to this, the RDO stable/train branch should be available and we actually need that

**Comment by hardys** [comment]
> let's hold on to this, the RDO stable/train branch should be available and we actually need that

This is already using the stable/train repos, just the current-tripleo pin?

Can you clarify what we're holding on?

**Comment by elfosardo** [comment]
@hardys I thought the stable/train branch was not available yet in RDO, but it is
we can merge this at the earliest convenience

**Pull request merged**
