### PR TITLE
Add space before ']'

### PR DESCRIPTION
**Pull request by MaXinjian**
Solve the following issues:
/bin/runironic-inspector: line 32: [: missing `]'
/bin/runironic-inspector: line 44: [: missing `]'

Signed-off-by: Ma Xinjian <maxj.fnst@fujitsu.com>

### CODE REVIEW

**Review by dtantsur — APPROVED** [review]
/test-integration
/lgtm

**Review by elfosardo — APPROVED** [review]

**Comment by dtantsur** [comment]
@MaXinjian could you update https://github.com/metal3-io/ironic-image/blob/master/scripts/runironic-inspector as well please? It will be used in the near future instead of this image.

**Pull request merged**
