### PR TITLE
Restart httpd reveser proxy when certificate is updated

### PR DESCRIPTION
**Pull request by namnx228**
This PR reload httpd when the TLS certificate is updated

### CODE REVIEW

**Comment by dtantsur** [comment]
How can this file change without restarting the container? I think a more container-native way of handling such changes is to restart a container.

**Comment by namnx228** [comment]
> How can this file change without restarting the container? I think a more container-native way of handling such changes is to restart a container.

@dtantsur The certificate is stored in a secret, and this secret is mounted to the container. So the certificate file can be updated by Kubelet when we edit the secret. 
It is a good point that restating the container is a more container-native approach. I will update this PR. Thanks for the suggestion.

**Comment by namnx228** [comment]
/cc @dtantsur 
After our discussion in the community meeting last week, I have added a variable that allows or disallows to restart the container. PTAL again. Thanks.

**Comment by elfosardo** [comment]
can this hold until https://github.com/metal3-io/ironic-image/pull/253 merges ?
otherwise we'll have to reopen it afterwards in the ironic-image repo

**Comment by namnx228** [comment]
> can this hold until [metal3-io/ironic-image#253](https://github.com/metal3-io/ironic-image/pull/253) merges ?
> otherwise we'll have to reopen it afterwards in the ironic-image repo

If the metal3-io/ironic-image#253 get merged, do we need to reopen this PR on ironic-image?

**Comment by elfosardo** [comment]
> > can this hold until [metal3-io/ironic-image#253](https://github.com/metal3-io/ironic-image/pull/253) merges ?
> > otherwise we'll have to reopen it afterwards in the ironic-image repo
> 
> If the [metal3-io/ironic-image#253](https://github.com/metal3-io/ironic-image/pull/253) get merged, do we need to reopen this PR on ironic-image?

yes, this needs to be migrated there in any case, although the other patch is close to merge

**Comment by dtantsur** [comment]
> If the metal3-io/ironic-image#253 get merged, do we need to reopen this PR on ironic-image?

Please do, the patch has merged. Closing because this is a substantial work item that we do not want to duplicate.

**Pull request closed without merging**
